---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        stringData: |
          type: git
          url: {{ .Values.gitUrl }}
          username: {{ "{{" }} (.{{ .Values.remoteSecretName }} | fromJSON).username {{ "}}" }}
          password: {{ "{{" }} (.{{ .Values.remoteSecretName }} | fromJSON).password {{ "}}" }}
  data:
  - secretKey: {{ .Values.remoteSecretName }}
    remoteRef:
      key: {{ .Values.remoteSecretName }}
