---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ .Values.appProject }}
  source:
    repoURL: {{ .Values.appRepoUrl }}
    targetRevision: {{ .Values.repoRevision }}
    path: {{ .Values.repoPath }}
  destination:
    server: {{ .Values.k8sApiUrl }}
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      {{- with .Values.syncPolicyAutomated }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    syncOptions:
    {{- with .Values.snycPolicyOptions }}
    {{- range . }}
    - {{ . }}
    {{- end }}
    {{- end }}
